/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prova;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laboratorio
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnG_LR = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_Titulo = new javax.swing.JTextField();
        txt_Autor = new javax.swing.JTextField();
        txt_AnoPubli = new javax.swing.JTextField();
        txt_Genero = new javax.swing.JTextField();
        txt_Isbn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdo_Livro = new javax.swing.JRadioButton();
        rdo_Revista = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Livro = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Revista = new javax.swing.JTable();
        btn_Inserir = new javax.swing.JButton();
        lbl_NumeroEd = new javax.swing.JLabel();
        txt_NumeroEd = new javax.swing.JTextField();
        lbl_NumeroPg = new javax.swing.JLabel();
        txt_NumeroPg = new javax.swing.JTextField();
        lbl_Editora = new javax.swing.JLabel();
        txt_Editora = new javax.swing.JTextField();
        lbl_Periodicidade = new javax.swing.JLabel();
        txt_Periodicidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo");

        jLabel2.setText("Autor");

        jLabel3.setText("Ano Publicacao");

        jLabel4.setText("Gênero");

        jLabel5.setText("ISBN");

        jLabel6.setText("O que deseja Inserir?");

        btnG_LR.add(rdo_Livro);
        rdo_Livro.setText("Livro");
        rdo_Livro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_LivroActionPerformed(evt);
            }
        });

        btnG_LR.add(rdo_Revista);
        rdo_Revista.setText("Revista");
        rdo_Revista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_RevistaActionPerformed(evt);
            }
        });

        tbl_Livro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Ano Publi", "Gênero", "ISBN", "Editora", "Nº Páginas"
            }
        ));
        jScrollPane1.setViewportView(tbl_Livro);

        tbl_Revista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titulo", "Autor", "Ano Publi", "Gênero", "ISBN", "Nº Edições", "Periodicidade"
            }
        ));
        jScrollPane2.setViewportView(tbl_Revista);

        btn_Inserir.setText("Inserir");
        btn_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InserirActionPerformed(evt);
            }
        });

        lbl_NumeroEd.setText("Nº edições");

        lbl_NumeroPg.setText("Nº Páginas");

        lbl_Editora.setText("Editora");

        lbl_Periodicidade.setText("Periodicidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Autor, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(txt_Titulo)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_AnoPubli, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(txt_Isbn)
                                            .addComponent(txt_Genero))))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Editora)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lbl_NumeroPg)
                                            .addGap(32, 32, 32)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txt_NumeroPg, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                                .addComponent(txt_Editora)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_Periodicidade)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_Periodicidade, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_NumeroEd)
                                                .addGap(32, 32, 32)
                                                .addComponent(txt_NumeroEd)))))
                                .addGap(41, 41, 41)
                                .addComponent(btn_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdo_Livro)
                                .addGap(18, 18, 18)
                                .addComponent(rdo_Revista)))
                        .addGap(0, 274, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rdo_Livro)
                    .addComponent(rdo_Revista))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Editora)
                    .addComponent(txt_Editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Inserir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NumeroPg)
                    .addComponent(txt_NumeroPg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_AnoPubli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NumeroEd)
                            .addComponent(txt_NumeroEd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Periodicidade)
                            .addComponent(txt_Periodicidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txt_Isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdo_LivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_LivroActionPerformed
      txt_NumeroPg.setVisible(true);
      txt_Editora.setVisible(true);
      lbl_NumeroPg.setVisible(true);
      lbl_Editora.setVisible(true);
      
      txt_NumeroEd.setVisible(false);
      txt_Periodicidade.setVisible(false);
      lbl_NumeroEd.setVisible(false);
      lbl_Periodicidade.setVisible(false);
    }//GEN-LAST:event_rdo_LivroActionPerformed

    private void rdo_RevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_RevistaActionPerformed
      txt_NumeroEd.setVisible(true);
      txt_Periodicidade.setVisible(true);
      lbl_NumeroEd.setVisible(true);
      lbl_Periodicidade.setVisible(true);
      
      txt_NumeroPg.setVisible(false);
      txt_Editora.setVisible(false);
      lbl_NumeroPg.setVisible(false);
      lbl_Editora.setVisible(false);
      
    }//GEN-LAST:event_rdo_RevistaActionPerformed

    private void btn_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InserirActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabelaLivro = (DefaultTableModel) tbl_Livro.getModel();
        DefaultTableModel tabelaRevista = (DefaultTableModel) tbl_Revista.getModel();
        
        if(rdo_Livro.isSelected()){
            Livro l = new Livro (txt_Titulo.getText(), 
                                 txt_Autor.getText(), 
                                 txt_AnoPubli.getText(), 
                                 txt_Genero.getText(),
                                 txt_Isbn.getText(),
                                 txt_Editora.getText(),
                                 txt_NumeroPg.getText()
            );
             ArrayList<Livro> listaLivro = new ArrayList<Livro>();
             listaLivro.add(l);
             
             for (Livro livro : listaLivro){
                 tabelaLivro.addRow(livro.obterDados());
             }
            JOptionPane.showMessageDialog(null, l.executaAcao(), "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if(rdo_Revista.isSelected()){
            Revista r = new Revista (txt_Titulo.getText(), 
                                 txt_Autor.getText(), 
                                 txt_AnoPubli.getText(), 
                                 txt_Genero.getText(),
                                 txt_Isbn.getText(),
                                 txt_NumeroEd.getText(),
                                 txt_Periodicidade.getText()
            );
             ArrayList<Revista> listaRevista = new ArrayList<Revista>();
             listaRevista.add(r);
             
             for (Revista revista : listaRevista){
                 tabelaRevista.addRow(revista.obterDados());
             }
            JOptionPane.showMessageDialog(null, r.executaAcao(), "Alerta", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            System.out.println("Selecione Livro ou Revista");
        }
    }//GEN-LAST:event_btn_InserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnG_LR;
    private javax.swing.JButton btn_Inserir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Editora;
    private javax.swing.JLabel lbl_NumeroEd;
    private javax.swing.JLabel lbl_NumeroPg;
    private javax.swing.JLabel lbl_Periodicidade;
    private javax.swing.JRadioButton rdo_Livro;
    private javax.swing.JRadioButton rdo_Revista;
    private javax.swing.JTable tbl_Livro;
    private javax.swing.JTable tbl_Revista;
    private javax.swing.JTextField txt_AnoPubli;
    private javax.swing.JTextField txt_Autor;
    private javax.swing.JTextField txt_Editora;
    private javax.swing.JTextField txt_Genero;
    private javax.swing.JTextField txt_Isbn;
    private javax.swing.JTextField txt_NumeroEd;
    private javax.swing.JTextField txt_NumeroPg;
    private javax.swing.JTextField txt_Periodicidade;
    private javax.swing.JTextField txt_Titulo;
    // End of variables declaration//GEN-END:variables
}
