/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

/**
 *
 * @author laboratorio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmArquivo = new javax.swing.JMenu();
        jSair = new javax.swing.JMenuItem();
        jmCadastro = new javax.swing.JMenu();
        jCadastroAluno = new javax.swing.JMenuItem();
        jEditarExcluirAluno = new javax.swing.JMenuItem();
        jCadastroProfessor = new javax.swing.JMenuItem();
        jEditarExcluirProfessor = new javax.swing.JMenuItem();
        jmRelatorio = new javax.swing.JMenu();
        jRelatorioAluno = new javax.swing.JMenuItem();
        jRelatorioProfessor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jmArquivo.setText("Arquivo");

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jmArquivo.add(jSair);

        jMenuBar1.add(jmArquivo);

        jmCadastro.setText("Cadastro");
        jmCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCadastroActionPerformed(evt);
            }
        });

        jCadastroAluno.setText("Cadastro de Aluno");
        jCadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jCadastroAluno);

        jEditarExcluirAluno.setText("Editar e excluir Aluno");
        jEditarExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarExcluirAlunoActionPerformed(evt);
            }
        });
        jmCadastro.add(jEditarExcluirAluno);

        jCadastroProfessor.setText("Cadastro de Professor");
        jCadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroProfessorActionPerformed(evt);
            }
        });
        jmCadastro.add(jCadastroProfessor);

        jEditarExcluirProfessor.setText("Editar e excluir Professor");
        jEditarExcluirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarExcluirProfessorActionPerformed(evt);
            }
        });
        jmCadastro.add(jEditarExcluirProfessor);

        jMenuBar1.add(jmCadastro);

        jmRelatorio.setText("Relatório");

        jRelatorioAluno.setText("Relatório de Aluno");
        jRelatorioAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioAlunoActionPerformed(evt);
            }
        });
        jmRelatorio.add(jRelatorioAluno);

        jRelatorioProfessor.setText("Relatório de Professor");
        jRelatorioProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRelatorioProfessorActionPerformed(evt);
            }
        });
        jmRelatorio.add(jRelatorioProfessor);

        jMenuBar1.add(jmRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCadastroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmCadastroActionPerformed

    private void jCadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroAlunoActionPerformed
        Inserir cadastro = new Inserir();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jCadastroAlunoActionPerformed

    private void jEditarExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarExcluirAlunoActionPerformed
        Editar editarExcluir = new Editar();
        editarExcluir.setVisible(true);
    }//GEN-LAST:event_jEditarExcluirAlunoActionPerformed

    private void jRelatorioAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioAlunoActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.setVisible(true);
    }//GEN-LAST:event_jRelatorioAlunoActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jSairActionPerformed

    private void jCadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroProfessorActionPerformed
        Inserir cadastro = new Inserir();
        cadastro.setVisible(true);
    }//GEN-LAST:event_jCadastroProfessorActionPerformed

    private void jEditarExcluirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarExcluirProfessorActionPerformed
        Editar editarExcluir = new Editar();
        editarExcluir.setVisible(true);
    }//GEN-LAST:event_jEditarExcluirProfessorActionPerformed

    private void jRelatorioProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRelatorioProfessorActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.setVisible(true);

    }//GEN-LAST:event_jRelatorioProfessorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jCadastroAluno;
    private javax.swing.JMenuItem jCadastroProfessor;
    private javax.swing.JMenuItem jEditarExcluirAluno;
    private javax.swing.JMenuItem jEditarExcluirProfessor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jRelatorioAluno;
    private javax.swing.JMenuItem jRelatorioProfessor;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenu jmArquivo;
    private javax.swing.JMenu jmCadastro;
    private javax.swing.JMenu jmRelatorio;
    // End of variables declaration//GEN-END:variables
}
