/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formulario;

import DAO.AlunoDAO;
import DAO.ProfessorDAO;
import beans.Aluno;
import beans.Professor;
import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class Editar extends javax.swing.JFrame {

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_Sexo = new javax.swing.ButtonGroup();
        txt_Nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_Consultar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_Id2 = new javax.swing.JTextField();
        btn_Atualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_Excluir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rdo_Aluno = new javax.swing.JRadioButton();
        rdo_Professor = new javax.swing.JRadioButton();
        txt_Idade = new javax.swing.JTextField();
        txt_Curso = new javax.swing.JTextField();
        lblDiciplina = new javax.swing.JLabel();
        txt_Disciplina = new javax.swing.JTextField();
        lblCurso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Idade");

        btn_Consultar.setText("Consultar");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });

        jLabel6.setText("Id atual");

        txt_Id2.setEditable(false);
        txt_Id2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id2ActionPerformed(evt);
            }
        });

        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        btn_Excluir.setText("Excluir");
        btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExcluirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Editar ou Excluir");
        jLabel2.setMaximumSize(new java.awt.Dimension(156, 16));
        jLabel2.setName(""); // NOI18N

        jLabel3.setText("Nome");

        rdo_Aluno.setText("Aluno");
        rdo_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_AlunoActionPerformed(evt);
            }
        });

        rdo_Professor.setText("Professor");
        rdo_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdo_ProfessorActionPerformed(evt);
            }
        });

        txt_Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CursoActionPerformed(evt);
            }
        });

        lblDiciplina.setText("Disciplina");

        lblCurso.setText("Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(rdo_Aluno)
                        .addGap(63, 63, 63)
                        .addComponent(rdo_Professor))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Atualizar)
                        .addGap(27, 27, 27)
                        .addComponent(btn_Excluir)
                        .addGap(36, 36, 36))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_Consultar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_Curso, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Nome, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Id2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                            .addComponent(txt_Idade, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(30, 30, 30)
                                        .addComponent(lblDiciplina)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(lblCurso))
                        .addContainerGap(57, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_Aluno)
                    .addComponent(rdo_Professor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btn_Consultar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCurso)
                    .addComponent(txt_Curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiciplina)
                    .addComponent(txt_Disciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Atualizar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        // TODO add your handling code here:
       if (rdo_Aluno.isSelected()){
        int idAluno = Integer.parseInt(txt_Id.getText());
        AlunoDAO aDAO = new AlunoDAO();

        Aluno a = aDAO.getAluno(idAluno);

        if (a==null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Aluno nao encontrada!");
        }
        else {
            txt_Id.setText(String.valueOf(a.getId()));
            txt_Nome.setText(a.getNome());
            txt_Idade.setText(a.getIdade());
            txt_Curso.setText(a.getCurso());
            txt_Id2.setText(txt_Id.getText());
        }
      }
       
       if (rdo_Professor.isSelected()){
        int idProfessor = Integer.parseInt(txt_Id.getText());
        ProfessorDAO pDAO = new ProfessorDAO();

        Professor p = pDAO.getProfessor(idProfessor);

        if (p==null){
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Aluno nao encontrada!");
        }
        else {
            txt_Id.setText(String.valueOf(p.getId()));
            txt_Nome.setText(p.getNome());
            txt_Idade.setText(p.getIdade());
            txt_Disciplina.setText(p.getDisciplina());
            txt_Id2.setText(txt_Id.getText());
        }
      }
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    private void txt_Id2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id2ActionPerformed

    }//GEN-LAST:event_txt_Id2ActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
       if(rdo_Aluno.isSelected()){
            Aluno a = new Aluno();
            a.setId (Integer.parseInt(txt_Id2.getText()));
            a.setNome(txt_Nome.getText());
            a.setIdade(txt_Idade.getText());
            a.setCurso(txt_Curso.getText());

            AlunoDAO aDAO = new AlunoDAO();
            aDAO.editar(a);
            limparFormulario();
       }
       
       if(rdo_Professor.isSelected()){
            Professor p = new Professor();
            p.setId (Integer.parseInt(txt_Id2.getText()));
            p.setNome(txt_Nome.getText());
            p.setIdade(txt_Idade.getText());
            p.setDisciplina(txt_Disciplina.getText());

            ProfessorDAO pDAO = new ProfessorDAO();
            pDAO.editar(p);
            limparFormulario();
       } 
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
        // TODO add your handling code here:
        if (rdo_Aluno.isSelected()){
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                AlunoDAO aDAO = new AlunoDAO();
                aDAO.excluir(Integer.parseInt(txt_Id.getText()));
                limparFormulario();
            }
        }
        
        if (rdo_Professor.isSelected()){
            int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir?", "Exclusão", JOptionPane.YES_NO_OPTION);
            if (resposta == JOptionPane.YES_OPTION){
                ProfessorDAO pDAO = new ProfessorDAO();
                pDAO.excluir(Integer.parseInt(txt_Id.getText()));
                limparFormulario();
            }
        }

    }//GEN-LAST:event_btn_ExcluirActionPerformed

    private void rdo_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_AlunoActionPerformed
        txt_Curso.setVisible(true);
        lblCurso.setVisible(true);

        txt_Disciplina.setVisible(false);
        lblDiciplina.setVisible(false);
    }//GEN-LAST:event_rdo_AlunoActionPerformed

    private void rdo_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdo_ProfessorActionPerformed
        txt_Curso.setVisible(false);
        lblCurso.setVisible(false);

        txt_Disciplina.setVisible(true);
        lblDiciplina.setVisible(true);
    }//GEN-LAST:event_rdo_ProfessorActionPerformed

    private void txt_CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editar().setVisible(true);
            }
        });
        
        
    }
    
    private void limparFormulario() {
        txt_Id.setText("");
        txt_Nome.setText("");
        txt_Idade.setText("");
        txt_Curso.setText("");
        txt_Disciplina.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.ButtonGroup btng_Sexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDiciplina;
    private javax.swing.JRadioButton rdo_Aluno;
    private javax.swing.JRadioButton rdo_Professor;
    private javax.swing.JTextField txt_Curso;
    private javax.swing.JTextField txt_Disciplina;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Id2;
    private javax.swing.JTextField txt_Idade;
    private javax.swing.JTextField txt_Nome;
    // End of variables declaration//GEN-END:variables
}
